name: LevelingPluginSMP
main: com.levelingsmp.LevelingPluginSMP
version: 1.0.0
api-version: "1.21"
author: Assistant
description: Leveling system: ground slam, dash, vitality, stat points and custom weapons.
commands:
  leveling:
    description: Open leveling GUI
    usage: /leveling
  levelinggive:
    description: Give items for testing (OP only)
    usage: /levelinggive
  ability1:
    description: Activate strength ability (ground slam) - stat
  ability2:
    description: Activate speed ability (dash) - stat
  ability3:
    description: Activate vitality ability - stat
  ability4:
    description: Weapon ability: strength sword
  ability5:
    description: Weapon ability: speed axe
  ability6:
    description: Weapon ability: vitality trident
permissions:
  levelingplugin.use:
    description: Open leveling GUI
    default: true
