name: LevelingPluginSMP
main: com.levelingplugin.LevelingPluginSMP
version: 1.0.0
api-version: 1.21
author: PurpOwnsYahh
description: "Leveling system with agility, strength, and vitality. Includes dash, ground slam, custom weapons, and stat reset item."

commands:
  leveling:
    description: Opens the leveling GUI
    usage: /<command>
  levelinggive:
    description: Gives a leveling item
    usage: /<command> <item>
